### PR TITLE
UNI-328 Raw+Aggregated Overlay Charts and Checkbox

### PR DESCRIPTION
**Pull request by brev**
UNI-328 = Raw+Aggregated Overlay Charts and Checkbox.
https://jira.numenta.com/browse/UNI-328

Both line charts now overlay correctly. Checkbox to toggle. Anomaly Bars moved to an underlay. Cleaned up right side and solved alignment/date issues. etc. Started a new basic functional test for viewing a sample metric chart.

Also:
- Rename a bunch of easy "Unicorn"s to "HTM Studio"
- Instantiate date's with moment instead of vanilla JS Date() object - correct TZ/DST handling.
- Styling and pixel pushing
- Lots of master-merging to stay current
- etc.

Please review @lscheinkman @marionleborgne.

### CODE REVIEW

**Comment by lscheinkman** [comment]
@brev the following tests are failing:
```
  1) Chart Sample Show should click checkbox to show Sample Chart:
     Uncaught CommandError: element (#main > main > section > div > div > div > div:nth-child(2) > div.dygraph-chart) still not visible after 500ms
      at elements("#main > main > section > div > div > div > div:nth-child(2) > div.dygraph-chart") - isVisible.js:49:17
      at isVisible("#main > main > section > div > div > div > div:nth-child(2) > div.dygraph-chart") - waitForVisible.js:45:22

  2) Chart Sample Show should be showing a Sample Chart with Create button:

      Uncaught AssertionError: false == true
      + expected - actual

      -false
      +true
      
      at Object.<anonymous> (chartSampleShow_test.js:84:16)
      at Object.exec (node_modules/webdriverio/build/lib/helpers/safeExecute.js:28:24)
      at Object.resolve (node_modules/webdriverio/build/lib/webdriverio.js:171:29)
      at node_modules/webdriverio/build/lib/webdriverio.js:424:32
      at _fulfilled (node_modules/webdriverio/node_modules/q/q.js:820:54)
      at self.promiseDispatch.done (node_modules/webdriverio/node_modules/q/q.js:849:30)
      at Promise.promise.promiseDispatch (node_modules/webdriverio/node_modules/q/q.js:782:13)
      at node_modules/webdriverio/node_modules/q/q.js:590:44
      at runSingle (node_modules/webdriverio/node_modules/q/q.js:123:13)
      at flush (node_modules/webdriverio/node_modules/q/q.js:111:13)

  3) Chart Sample Show should NOT be showing the Default App Background anymore:

      Uncaught AssertionError: true == false
      + expected - actual

      -true
      +false
      
      at Object.<anonymous> (chartSampleShow_test.js:92:16)
      at Object.exec (node_modules/webdriverio/build/lib/helpers/safeExecute.js:28:24)
      at Object.resolve (node_modules/webdriverio/build/lib/webdriverio.js:171:29)
      at node_modules/webdriverio/build/lib/webdriverio.js:424:32
      at _fulfilled (node_modules/webdriverio/node_modules/q/q.js:820:54)
      at self.promiseDispatch.done (node_modules/webdriverio/node_modules/q/q.js:849:30)
      at Promise.promise.promiseDispatch (node_modules/webdriverio/node_modules/q/q.js:782:13)
      at node_modules/webdriverio/node_modules/q/q.js:590:44
      at runSingle (node_modules/webdriverio/node_modules/q/q.js:123:13)
      at flush (node_modules/webdriverio/node_modules/q/q.js:111:13)
```

**Comment by lscheinkman** [comment]
The chart scrolls to a different position  "Show non-aggregated data" checkbox is toggled

**Comment by brev** [comment]
thanks @lscheinkman looking into these now

**Comment by brev** [comment]
@lscheinkman @marionleborgne Pulled new functional test, it wasn't working for me from home either, I'll look into the timeouts separately. (Need to massage the new functional test framework just a bit).

**Comment by brev** [comment]
ok, merging now to get this Beast PR out of the way. 
Will make a couple of fixes in a new PR soon:
1. Chart position changes when toggling new ShowNonAgg checkbox
2. LeftNav checkboxes seem to take 2 clicks now
.. and any other feedback that comes up.
thanks @lscheinkman. cc @marionleborgne @cbaranski

**Pull request merged**
