### PR TITLE
UNI-417: Move "Show Aggregation" checkbox to the top

### PR DESCRIPTION
**Pull request by lscheinkman**
@marionleborgne sub task of UNI-385

### CODE REVIEW

**Comment by marionleborgne** [comment]
LGTM except some minor styling issues:
1. The text and buttons is aligned, except for the left title (see screenshot below)
2. The checkbox can be moved closer to the buttons (e.g. leave about about the same amount of space between checkbox text & button as we have between the buttons) 

screen shot 2016-04-20 at 3 54 24 pm

**Comment by lscheinkman** [comment]
@marionleborgne  I used the same spacing as the screenshot attached to the JIRA

**Comment by lscheinkman** [comment]
@marionleborgne I've updated the spacing pr our discussion, let me know if it works for you

**Comment by marionleborgne** [comment]
👍 for alignment of the text and spacing. Isn't the checkbox still misaligned though? (not the text, just the checkbox)

**Comment by lscheinkman** [comment]
I'm not sure, I have to see on your screen

**Comment by marionleborgne** [comment]
@lscheinkman never mind, it's really just couple of pixels off but that's how material UI does it. So you can merge the PR 👍

**Pull request merged**
