### PR TITLE
UNI-404 Use big round numbers on the y axis

### PR DESCRIPTION
**Pull request by mrcslws**
Note that it adds a new module. You can use `npm install d3-scale`.

@marionleborgne

### CODE REVIEW

**Comment by marionleborgne** [comment]
@mrcslws It looks very nice 👍 

I need to test it on more datasets though. I looked at the NYC and server data so far.

**Comment by marionleborgne** [comment]
htm studio v0 0 1

**Comment by marionleborgne** [comment]
Once #803 is merged we can review this PR @mrcslws

**Comment by mrcslws** [comment]
@marionleborgne alright, this is ready. It adds 2px of padding on the top and bottom, like we mentioned in https://github.com/numenta/numenta-apps/pull/803.

**Comment by marionleborgne** [comment]
👍 Thanks @mrcslws

**Pull request merged**
