### PR TITLE
Remove py_region_test that has been moved.

### PR DESCRIPTION
**Pull request by scottpurdy**

### CODE REVIEW

**Comment by jcasner** [comment]
Has the test moved or been removed?  If it's just moved, shouldn't we be executing it from the new location?

**Comment by scottpurdy** [comment]
https://github.com/numenta/nupic.core/issues/572

**Comment by jcasner** [comment]
Do we need a JIRA to add it back to Jenkins after numenta/nupic.core#572 is fixed?

**Comment by scottpurdy** [comment]
Sure?

**Pull request merged**
