### PR TITLE
ENG-94 Make sure nextCallStartTime advances in AWSResourceAdapterBase.getMetricData() when no data was collected for the requested range to prevent Cloudwatch metric data collection stall

### PR DESCRIPTION
**Pull request by vitaly-krugl**

### CODE REVIEW

**Comment by vitaly-krugl** [comment]
@scottpurdy, I think this should fix it. If you agree with the concept, then I will add a unit test to this PR.

**Comment by vitaly-krugl** [comment]
@scottpurdy, these fixes are now accompanied by unit tests that pass and everything is ready for review.

**Comment by scottpurdy** [comment]
:+1:

**Comment by vitaly-krugl** [comment]
Integration tests passed on my dev laptop. Merging...

CC @scottpurdy

**Pull request merged**
