### PR TITLE
UNI-568 Support excel default format on Windows

### PR DESCRIPTION
**Pull request by marionleborgne**
@lscheinkman @cbaranski

### CODE REVIEW

**Comment by lscheinkman** [comment]
File __CB new5.csv__ (attached to JIRA) failed with the following error: 
```
    err: {"errorText": "negative dimensions are not allowed", 
"diagnosticInfo": "Traceback (most recent call last):
  File \"build/bdist.macosx-10.5-x86_64/egg/unicorn_backend/param_finder_runner.py\", line 203, in main
  File \"build/bdist.macosx-10.5-x86_64/egg/unicorn_backend/param_finder.py\", line 243, in findParameters
    medianSamplingIntervalInMs)\n  File \"build/bdist.macosx-10.5-x86_64/egg/unicorn_backend/param_finder.py\", line 383, in _resampleData
    newTimeStamps = numpy.empty(nSampleNew, dtype=\"datetime64[ms]\")\nValueError: negative dimensions are not allowed
"}
    
    --
    inputOpt: {
      "csv": "~/Library/Application Support/HTM Studio/files/CB new5.csv",
      "rowOffset": 0,
      "timestampIndex": 0,
      "valueIndex": 1,
      "datetimeFormat": "%m/%d/%Y"
    }
22:59:33.431Z ERROR htmstudio:  (metricId=527866a0dc6dc03e!bc654d7c96f073fb, event=close, code=1)
    inputOpt: {
      "csv": "~/Library/Application Support/HTM Studio/files/CB new5.csv",
      "rowOffset": 0,
      "timestampIndex": 0,
      "valueIndex": 1,
      "datetimeFormat": "%m/%d/%Y"
    }
```

**Comment by marionleborgne** [comment]
@lscheinkman I found why. It's because the data in the file is not in the right order

```
(Pdb) timestamps[-1]
numpy.datetime64('1930-02-07T00:00:00.000Z')
(Pdb) timestamps[0]
numpy.datetime64('2016-05-31T17:00:00.000-0700')
```

**Comment by marionleborgne** [comment]
@lscheinkman it should work now. Try again? This is what I get:

screen shot 2016-06-22 at 5 25 25 pm

**Comment by marionleborgne** [comment]
This fix has the nice effect that the data does not need to be ordered chronologically anymore :-)

**Comment by lscheinkman** [comment]
👍  Works now

**Comment by marionleborgne** [comment]
@vitaly-krugl the data checker does not catch the "unordered data case", but it's a good point and it probably should. However it's out of the scope of this PR. I created a JIRA (UNI-576) for this enhancement so that we can prioritize it in our task list.

**Pull request merged**
