### PR TITLE
UNI-445 "About HTM Studio" and "Provide Feedback"

### PR DESCRIPTION
**Pull request by mrcslws**
cc @marionleborgne

### CODE REVIEW

**Comment by marionleborgne** [comment]
LGTM 👍 thanks @mrcslws

**Comment by marionleborgne** [comment]
@lscheinkman this is what the about menu looks like:
screen shot 2016-05-12 at 11 50 27 pm

I think it looks fine. it's not a material-ui menu, so i thought i would just run it by you.

When we have all the right links (EULA and Feedback form) live on numenta.com i'll add/update the links accordingly.

**Comment by marionleborgne** [comment]
When we have all the right links (EULA and Feedback form) live on numenta.com i'll add/update the links accordingly. But right now we can merge, since the links won't be up until next monday.

**Comment by brev** [comment]
@marionleborgne numenta.com URLs 
https://jira.numenta.com/browse/WEB-76?focusedCommentId=52108&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-52108

**Comment by marionleborgne** [comment]
Thanks @brev. I'll update the links in a separate PR

**Pull request merged**
