### PR TITLE
TAUR-873 Log scores in result_quality_test.py when the test passes to help with debugging and comparisons

### PR DESCRIPTION
**Pull request by vitaly-krugl**

### CODE REVIEW

**Comment by vitaly-krugl** [comment]
CC @scottpurdy

**Comment by scottpurdy** [comment]
I find the new function a little confusing. Why not leave as is and just concatenate either the success or the failure message with the common part depending on the two cases? But otherwise seems fine.

**Comment by vitaly-krugl** [comment]
@scottpurdy, that would work, too. Is it worthwhile to make the suggested change?

**Comment by scottpurdy** [comment]
@vitaly-krugl - your call

**Pull request merged**
