### PR TITLE
Use forked cxfreeze in which use of shutil.copystat() is optional, al…

### PR DESCRIPTION
**Pull request by oxtopus**
…lowing use on OS X El Capitan

cc @lscheinkman

### CODE REVIEW

**Comment by lscheinkman** [comment]
After installing and building:
```
$ pip install -r py/requirements.txt --user
$ npm install
$ npm run build
```
I got this error:
```
$ dist/model_runner 
Traceback (most recent call last):
  File "/Users/lscheinkman/Library/Python/2.7/lib/python/site-packages/cx_Freeze/initscripts/Console.py", line 21, in <module>
    exec(code, m.__dict__)
  File "/Users/lscheinkman/Documents/work/github/numenta/products/unicorn/py/unicorn_backend/model_runner.py", line 56, in <module>
    from nupic.frameworks.opf.modelfactory import ModelFactory
  File "/private/var/folders/tt/t0vptb4x2w944tqk7_c3kyt00000gn/T/pip-build-SfdKmo/nupic/nupic/frameworks/opf/modelfactory.py", line 32, in <module>
  File "/private/var/folders/tt/t0vptb4x2w944tqk7_c3kyt00000gn/T/pip-build-SfdKmo/nupic/nupic/frameworks/opf/clamodel.py", line 44, in <module>
  File "/private/var/folders/tt/t0vptb4x2w944tqk7_c3kyt00000gn/T/pip-build-SfdKmo/nupic/nupic/encoders/__init__.py", line 31, in <module>
  File "/private/var/folders/tt/t0vptb4x2w944tqk7_c3kyt00000gn/T/pip-build-SfdKmo/nupic/nupic/encoders/geospatial_coordinate.py", line 31, in <module>
  File "/Users/lscheinkman/local/lib/python2.7/site-packages/pyproj-1.9.3-py2.7-macosx-10.11-intel.egg/pyproj/__init__.py", line 343, in __new__
    return _proj.Proj.__new__(self, projstring)
  File "_proj.pyx", line 80, in _proj.Proj.__cinit__ (_proj.c:950)
RuntimeError: no system list, errno: 2
```
It looks like there were some changes to the way `cx_freeze` works from version `4.3.4` to `5.0`

**Comment by lscheinkman** [comment]
@marionleborgne Can you review this one as well? It looks like it may need some changes in the way `pyproj` is packaged

CC: @oxtopus

**Comment by marionleborgne** [comment]
@lscheinkman yes I am able to reproduce the same error. I am investigating how to package `pyproj` differently

**Comment by lscheinkman** [comment]
@marionleborgne, @oxtopus Is this PR still relevant for unicorn?

**Comment by marionleborgne** [comment]
@lscheinkman indeed, this issue is not relevant anymore This is what made us decide to change our strategy to package Python in Unicorn. We can close this issue. I sent out an email today with an update for OSX: 
* (...) I created a fresh build box (OSX 10.10 with VMware fusion) that has a portable python distribution with nupic, nupic.bindings, and all the remaining dependencies. I have documented the build process and created a snapshot of the VM. So we are good with OSX now. *

This approach is more stable than the freezing tools.  An additional advantage is that we can spawn the model runner as a python process, regardless of wether we are using the dev version of unicorn or the built desktop app. This has already been rolled in as part of https://github.com/numenta/numenta-apps/pull/479

The one thing I need to do now is to update the build script in electron (we do not need freezing tools anymore). I'll create a separate JIRA for myself to track this task.

**Pull request closed without merging**
