### PR TITLE
UNI-505 added install GIF

### PR DESCRIPTION
**Pull request by marionleborgne**
I added a new loading GIF in `build/install-spinner.gif`.

@oxtopus do you mind testing this? I am still unable to build unicorn fully on my windows VM.

### CODE REVIEW

**Comment by oxtopus** [comment]
It works, but takes up almost the whole screen at 1024x768

untitled

untitled2

**Comment by marionleborgne** [comment]
Thanks. I'll update the size.

**Comment by marionleborgne** [comment]
@oxtopus updated. Let me know if it's better. Thanks!

**Comment by oxtopus** [comment]
Much better 👍 

untitled2

**Pull request merged**
