### PR TITLE
TAUR-851 TAUR-1272 Update rabbitmqadmin script and add taurus user to rabbit

### PR DESCRIPTION
**Pull request by jcasner**
@oxtopus @unixorn please review

### CODE REVIEW

**Comment by oxtopus** [comment]
:+1:

**Comment by unixorn** [comment]
:rocket:

**Comment by oxtopus** [comment]
Looks like I also need:

```
rabbitmqctl set_permissions -p / taurus ".*" ".*" ".*"
```

Or else, I can't create channels, exchanges, queues, etc.

**Comment by jcasner** [comment]
@oxtopus see lines 75-79; I think those set the perms you need...

**Comment by oxtopus** [comment]
Yes, indeed.  My bad.

**Pull request merged**
