### PR TITLE
TAUR-899 Removing duplicate tests from collectorsdb and monitorsdb

### PR DESCRIPTION
**Pull request by rmccall84**
Fixes https://jira.numenta.com/browse/TAUR-899 and https://jira.numenta.com/browse/TAUR-900

### CODE REVIEW

**Comment by rmccall84** [comment]
For reference the test was already here https://github.com/rmccall84/numenta-apps/blob/master/nta.utils/tests/unit/sqlalchemy_retry_on_transient_error_test.py

**Comment by rmccall84** [comment]
@scottpurdy Found another loose end to tie up. Please CR

**Comment by scottpurdy** [comment]
Looks fine. I am assuming the test that is removed from the two files exists somewhere else?

**Comment by rmccall84** [comment]
@scottpurdy yes in nta.utils (https://github.com/rmccall84/numenta-apps/blob/master/nta.utils/tests/unit/sqlalchemy_retry_on_transient_error_test.py) BTW, I don't have write access so plz merge.

**Pull request merged**
