### PR TITLE
Fix package names

### PR DESCRIPTION
**Pull request by scottpurdy**
@oxtopus @vitaly-krugl 

Suggestions for testing are welcome. I was able to run tests and haven't found any issues but I'd be surprised if there aren't still some lingering.

### CODE REVIEW

**Comment by oxtopus** [comment]
I set up a plan branch for this at https://ci.numenta.com/browse/TAUR-TAUR3-1

It's tracking my fork, but you may want to configure it to track yours to iterate on changes.

**Comment by scottpurdy** [comment]
@oxtopus thanks

**Comment by oxtopus** [comment]
The bamboo build tasks and deployment plans will need to be fixed to use the new paths.

**Comment by oxtopus** [comment]
LGTM, but need to have a plan for the pipelines before I'm comfortable merging since they will certainly break as they are.

**Comment by scottpurdy** [comment]
@oxtopus I got everything working in a plan branch. What else should I be looking into? The deployment setup in Bamboo definitely needs a look. Do you think we should work that out in staging now?

**Comment by scottpurdy** [comment]
https://ci.numenta.com/browse/TAUR-TAUR3

**Comment by oxtopus** [comment]
It's your call.  We can prepare and configure a new environment relatively easily, but really, we can work out whatever we need in staging.  That's what it's there for.

**Comment by vitaly-krugl** [comment]
💯

**Pull request merged**
