### PR TITLE
UNI-565 updated text and redirecting to the FAQ with info about the license

### PR DESCRIPTION
**Pull request by marionleborgne**
@lscheinkman @cbaranski

### CODE REVIEW

**Comment by lscheinkman** [comment]
When clicking on the link the main window is replaced with the Web Page and the user is stuck on that page.
The link should open a new browser window instead.
screen shot 2016-06-22 at 4 07 49 pm

**Comment by marionleborgne** [comment]
oh thanks! I'll update.

**Comment by marionleborgne** [comment]
@lscheinkman it should be fixed now. Let me know if works for you.

**Comment by lscheinkman** [comment]
👍  It worked

**Pull request merged**
