### PR TITLE
IMBU-50 Load models if cache exists, save upon initial training

### PR DESCRIPTION
**Pull request by oxtopus**
This also adds `destructive-build-and-refresh-container.sh` and `graceful-build-and-refresh-container.sh` as docker workflow helpers.

### CODE REVIEW

**Comment by oxtopus** [comment]
@BoltzmannBrain This is ready, but I'm experiencing some failures in htmresearch codebase after making these changes.  For example, in https://github.com/numenta/nupic.research/blob/master/htmresearch/frameworks/nlp/classify_windows.py#L102 and https://github.com/numenta/nupic.research/blob/master/htmresearch/frameworks/nlp/classification_model.py#L331 it fails because the value is a list and not a numpy array, causing the `.tolist()` method to fail.

Those snippets of code are also somewhat problematic because if `p.get("labels", None)` returned `None`, the `.tolist()` on the return would fail, too.

Another issue is in https://github.com/numenta/nupic.research/blob/master/htmresearch/frameworks/nlp/classify_fingerprint.py#L115 wherein `count` may not be initialized, causing another error.

AFAIK, these issues are not related to the load/save functionality.  But they may be side effects.

**Comment by BoltzmannBrain** [comment]
@oxtopus I merged some changes into nupic.research ([#381](https://github.com/numenta/nupic.research/pull/381)) to address these issues, thank you for bringing them up. Please run again.

**Comment by BoltzmannBrain** [comment]
LGTM but I'm having issues running Imbu (after rebuilding nupic and nupic.core), the page is stuck on the blank "Loading..." screen.
@lscheinkman will you please review this PR?

**Comment by lscheinkman** [comment]
@oxtopus Please add `cache` to `.gitignore`

@BoltzmannBrain 
I've update `nupic` image to the latest build using `docker pull numenta/nupic`.
And got this error:
```
[pid: 20|app: 0|req: 17/17] 192.168.99.1 () {48 vars in 817 bytes} [Thu Dec 17 17:51:15 2015] POST /fluent/CioWindows => generated 2 bytes in 9 msecs (HTTP/1.1 200) 6 headers in 275 bytes (2 switches on core 0)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/web.py-0.37-py2.7.egg/web/application.py", line 239, in process
    return self.handle()
  File "/usr/local/lib/python2.7/dist-packages/web.py-0.37-py2.7.egg/web/application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "/usr/local/lib/python2.7/dist-packages/web.py-0.37-py2.7.egg/web/application.py", line 420, in _delegate
    return handle_class(cls)
  File "/usr/local/lib/python2.7/dist-packages/web.py-0.37-py2.7.egg/web/application.py", line 396, in handle_class
    return tocall(*args)
  File "engine/fluent_api.py", line 449, in POST
    response = g_fluent.query(modelName, data)
  File "engine/fluent_api.py", line 399, in query
    sortedDistances = g_models[model].queryModel(text, preprocess=False)
  File "engine/fluent_api.py", line 171, in queryModel
    return self._submitTask(QueryModelTask._make([query, preprocess]))
  File "engine/fluent_api.py", line 204, in _submitTask
    raise outputValue
IndexError: Number of protoype distances must match number of samples trained on.
```

**Comment by BoltzmannBrain** [comment]
That error gets raised [here](https://github.com/numenta/nupic.research/blob/master/htmresearch/frameworks/nlp/classify_windows.py#L189-L190) when querying the model.
It's unclear to me yet why this is happening (there aren't any relevant changes to the kNN classifier in nupic). I also notice when I run the [htmresearch imbu runner](https://github.com/numenta/nupic.research/blob/master/projects/nlp/imbu_runner.py) I'm getting differently scaled overlap scores.

**Comment by oxtopus** [comment]
The latest error I'm seeing is: 

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "engine/fluent_api.py", line 328, in createModel
    modelProxy.encodeSamples(samples)
  File "engine/fluent_api.py", line 163, in encodeSamples
    return self._submitTask(EncodeSamplesTask._make([samples]))
  File "engine/fluent_api.py", line 204, in _submitTask
    raise outputValue
ConnectionError: None: Max retries exceeded with url: /rest/terms?get_fingerprint=True&retina_name=en_associative&max_results=10&term=whiteboards&start_index=0 (Caused by redirect)
```

**Comment by lscheinkman** [comment]
@BoltzmannBrain FYI, The version from `master` works just fine. No errors.
The version from this branch fails with this error:
```
[pid: 21|app: 0|req: 41/41] 192.168.99.1 () {48 vars in 833 bytes} [Fri Dec 18 22:21:48 2015] POST /fluent/CioWordFingerprint => generated 4142 bytes in 8 msecs (HTTP/1.1 200) 6 headers in 275 bytes (2 switches on core 0)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/web.py-0.37-py2.7.egg/web/application.py", line 239, in process
    return self.handle()
  File "/usr/local/lib/python2.7/dist-packages/web.py-0.37-py2.7.egg/web/application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "/usr/local/lib/python2.7/dist-packages/web.py-0.37-py2.7.egg/web/application.py", line 420, in _delegate
    return handle_class(cls)
  File "/usr/local/lib/python2.7/dist-packages/web.py-0.37-py2.7.egg/web/application.py", line 396, in handle_class
    return tocall(*args)
  File "engine/fluent_api.py", line 449, in POST
    response = g_fluent.query(modelName, data)
  File "engine/fluent_api.py", line 399, in query
    sortedDistances = g_models[model].queryModel(text, preprocess=False)
  File "engine/fluent_api.py", line 171, in queryModel
    return self._submitTask(QueryModelTask._make([query, preprocess]))
  File "engine/fluent_api.py", line 204, in _submitTask
    raise outputValue
IndexError: Number of protoype distances must match number of samples trained on.
```

**Comment by BoltzmannBrain** [comment]
@lscheinkman I tested the save and load methods for the models and they work as expected.

**Comment by oxtopus** [comment]
I get the same error as @lscheinkman now and I've added some debug output to help show what's going on:

```
<htmresearch.frameworks.nlp.classify_fingerprint.ClassificationModelFingerprint object at 0x7f7fe45d0fd0> patterns[i]["labels"] -> []
<htmresearch.frameworks.nlp.classify_fingerprint.ClassificationModelFingerprint object at 0x7f7fe45d0fd0> count -> 1 sampleReference -> []
<htmresearch.frameworks.nlp.classify_fingerprint.ClassificationModelFingerprint object at 0x7f7fe45d0fd0> trainModel( 33 )
<htmresearch.frameworks.nlp.classify_fingerprint.ClassificationModelFingerprint object at 0x7f7fe45d0fd0> bitmap -> [    3     7     8 ..., 16348 16381 16382]
<htmresearch.frameworks.nlp.classify_fingerprint.ClassificationModelFingerprint object at 0x7f7fe45d0fd0> patterns[i]["labels"] -> []
<htmresearch.frameworks.nlp.classify_fingerprint.ClassificationModelFingerprint object at 0x7f7fe45d0fd0> count -> 1 sampleReference -> []
<htmresearch.frameworks.nlp.classify_fingerprint.ClassificationModelFingerprint object at 0x7f7fe45d0fd0> trainModel( 34 )
<htmresearch.frameworks.nlp.classify_fingerprint.ClassificationModelFingerprint object at 0x7f7fe45d0fd0> bitmap -> [    3     6     7 ..., 16374 16375 16376]
<htmresearch.frameworks.nlp.classify_fingerprint.ClassificationModelFingerprint object at 0x7f7fe45d0fd0> patterns[i]["labels"] -> []
<htmresearch.frameworks.nlp.classify_fingerprint.ClassificationModelFingerprint object at 0x7f7fe45d0fd0> count -> 1 sampleReference -> []
```

Looking at https://github.com/numenta/nupic.research/blob/master/htmresearch/frameworks/nlp/classify_fingerprint.py#L109-L117, it's clear that `self.patterns[i]["labels"]` is empty.  As a result, the loop is never entered, which explains why previously `count` was never being initialized.  I'm going to dig further to see why `self.patterns[i]["labels"]` is empty.

**Comment by oxtopus** [comment]
@BoltzmannBrain AFAIK, `self.patterns[i]["labels"]` is empty because the call to `readCSV()` includes `numlabels=0`.  If I bump that up to, say, 3, I encounter a completely different error:

```
Traceback (most recent call last):
  File "engine/fluent_api.py", line 107, in run
    output = self.modelObj.trainModel(i=obj.i)
  File "/usr/local/lib/python2.7/dist-packages/htmresearch-0.0.1-py2.7.egg/htmresearch/frameworks/nlp/classify_fingerprint.py", line 116, in trainModel
    self.classifier.learn(bitmap, label, isSparse=self.encoder.n)
  File "/usr/local/lib/python2.7/dist-packages/nupic-0.3.4-py2.7.egg/nupic/algorithms/KNNClassifier.py", line 523, in learn
    self._categoryList.append(int(inputCategory))
ValueError: invalid literal for int() with base 10: 'kitchen'
```

So, it seems there's something wrong with the preparation and handling of data somewhere along the pathway.

What should `numlabels` (e.g. https://github.com/oxtopus/numenta-apps/blob/IMBU-50/imbu/engine/fluent_api.py#L273) be?  It was `0` before my changes.

Do you have any insight to offer re: `ValueError` raised in KNNClassifier.py?

**Comment by oxtopus** [comment]
I've sync'ed with master and set numLabels=3.  Here's an example output in logs/uwsgi.log that shows the error:

```
waiting for models...
Attempting to load from /opt/numenta/imbu/cache/CioWordFingerprint
Attempting to load from /opt/numenta/imbu/cache/CioWindows
Attempting to load from /opt/numenta/imbu/cache/CioDocumentFingerprint
Could not load model from '/opt/numenta/imbu/cache/CioWindows/model.pkl'.
Could not load model from '/opt/numenta/imbu/cache/CioWordFingerprint/model.pkl'.
Model failed to load from /opt/numenta/imbu/cache/CioWindows Let's train it from scratch.
Model failed to load from /opt/numenta/imbu/cache/CioWordFingerprint Let's train it from scratch.
Could not load model from '/opt/numenta/imbu/cache/CioDocumentFingerprint/model.pkl'.
Model failed to load from /opt/numenta/imbu/cache/CioDocumentFingerprint Let's train it from scratch.
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "engine/fluent_api.py", line 337, in createModel
    modelProxy.trainModel(i)
  File "engine/fluent_api.py", line 169, in trainModel
    return self._submitTask(TrainModelTask._make([i]))
  File "engine/fluent_api.py", line 206, in _submitTask
    raise outputValue
ValueError: invalid literal for int() with base 10: 'kitchen'
```

**Comment by BoltzmannBrain** [comment]
@oxtopus it is definitely supposed to be `numLabels=0`. This param is used for labeled classification data in other experiments. "kitchen" is one of these labels, but the classifier is not expecting labels here, hence the ValueError. I'll investigate the other error later when I have time. Thank you for adding the debug output.

**Comment by oxtopus** [comment]
@BoltzmannBrain See latest.  I restored numLabels to 0, but also made a number of changes, including bumping the nupic version to match latest release as well as support local checkouts of htmresearch.

If you map the /opt/numenta/nupic.research directory to your nupic.research clone, it will use that as opposed to a fresh clone isolated to the container.  For example, I have a `env.sh` file (see below), that I can `source`, and then `destructive-build-and-refresh-container.sh`/`graceful-build-and-refresh-container.sh` will map the dir in the `docker run` command.

Contents of `env.sh`:

```eval $(docker-machine env dev)
export IMBU_DOCKER_EXTRAS="-v `pwd`/cache:/opt/numenta/imbu/cache -v /Users/amarshall/nta/nupic.research:/opt/numenta/nupic.research"
export CORTICAL_API_KEY="3ba91980-9794-11e5-9e69-03c0722e0d16"
export IMBU_RETINA_ID="en_associative"
```

Usage:

```
source env.sh
./destructive-build-and-refresh-container.sh
```

Then, to `docker exec` into the running container to debug:

```
docker exec -ti imbu /bin/bash
```

Then, if you make any changes to either htmresearch or imbu locally, you can call `./destructive-build-and-refresh-container.sh` to apply the changes cleanly, or `docker restart imbu` to do it quickly.

**Comment by oxtopus** [comment]
re:
> it is definitely supposed to be numLabels=0

If that's the case, then I don't understand the relationship between https://github.com/numenta/nupic.research/blob/master/htmresearch/frameworks/nlp/classify_fingerprint.py#L112-L114 and https://github.com/numenta/nupic.research/blob/master/htmresearch/frameworks/nlp/classification_model.py#L249-L251.  Without labels, `sampleReference` is never touched, which explains the error.  What I don't understand, however, is how it ever worked, or why it's suddenly an issue in this PR.

**Comment by oxtopus** [comment]
As of 09a52c6 I've disabled the load/save process and will merge this as is.  The PR without the load/save works as expected.  I will followup separately with a PR re-enabling load/save.

**Comment by BoltzmannBrain** [comment]
@oxtopus `sampleReference` is populated when each model runs through `trainModel()`, but on the [condition there are patterns to train on](https://github.com/numenta/nupic.research/blob/master/htmresearch/frameworks/nlp/classify_fingerprint.py#L111). With `numLabels=0` this still works as expected because [the labels array for each pattern gets defaulted to = `array([-1])`](https://github.com/numenta/nupic.research/blob/master/htmresearch/frameworks/nlp/classification_model.py#L301). In your debug output above we see the behavior to default all labels arrays to `array([-1])` is not working.

**Pull request merged**
