### PR TITLE
Only install numpy on instances that actually need it.

### PR DESCRIPTION
**Pull request by unixorn**
Bad practice to install software on machines that don't use it.

### CODE REVIEW

**Comment by unixorn** [comment]
@jcasner, @shantanoo please CR.
Make sure to also merge [numenta-private-salt-infrastructure/pull/97](https://github.com/GrokSolutions/numenta-private-salt-infrastructure/pull/97) when this is merged.

**Comment by jcasner** [comment]
I'm only neutral at best on this... I would much rather have python dependencies be managed by the apps themselves via requirements.txt.  While this is circumventing a known issue, I think the safer approach is to include a `pip install numpy==1.9.2` command in the `install-grok.sh` and `install-taurus.sh` files and leave all python requirements out of salt entirely.

**Comment by unixorn** [comment]
I'm even happier with that solution.

**Comment by jcasner** [comment]
:+1:

**Comment by oxtopus** [comment]
@jcasner let's talk about this when I get back from vacation...

**Comment by jcasner** [comment]
@oxtopus that sounds awesome - might need to wait until I'm back from vacation - I'm probably taking next week off

**Pull request merged**
