### PR TITLE
UNI-380 Override range selector handle styling. Loading indicators match style.

### PR DESCRIPTION
**Pull request by brev**
UNI-380 Override range selector handle styling. Loading indicators match style.
- Range selector is now styled as per mockups.
- Page init "Loading.." message now has animated icon.
- Left Nav metric status indicator "Loading" icon and animation now match the rest.
- Unit and Integration test fixes
- etc.

https://jira.numenta.com/browse/UNI-380

Ready for review @marionleborgne.  cc @lscheinkman @cbaranski

### CODE REVIEW

**Comment by brev** [comment]
p.s. @marionleborgne I think `npm run test` is failing after your recent big merge ? thanks

**Comment by marionleborgne** [comment]
Thanks @brev. Having a look now (and will fix the tests if they are broken)

**Comment by marionleborgne** [comment]
@brev FYI, the CI server is down and I can't run npm install. I'll try later today

**Comment by marionleborgne** [comment]
@brev I managed to circumvent the problem with no being able to download the portable python distribution. You new nav bar looks great. 

One detail that I noticed it that the anomaly bars are ticking out a tiny bit from the range selector (at the top). See screenshot: 
anomaly bars sticking out a bit

**Comment by marionleborgne** [comment]
And the test does fail indeed. Here's what I got
```
  24 passing (283ms)
  1 failing

  1) Utils common-utils #anomalyScale:

      AssertionError: 0.1 == 0.2
      + expected - actual

      -0.1
      +0.2
```
Do you have the same error?
I think I know where it comes from, I'll submit a separate PR.

**Comment by brev** [comment]
@marionleborgne Looking into that extra pixel, thanks.

Yeah, same unit test failure for me too. 3 integration test failures that I don't recognize also.

**Comment by marionleborgne** [comment]
FYI, I fixed the unit test, but some integration tests are failing too. It's an easy fix (we updated the model params)

**Comment by marionleborgne** [comment]
@brev I fixed the tests. Let me know if it works for you too.

**Comment by brev** [comment]
ok @marionleborgne I removed that hanging pixel, does this look better?

**Comment by marionleborgne** [comment]
@brev yes it does :+1: 

@mrcslws and other people who tested the app had good feedback about the selector: it would be good to incorporate a "point and click" behavior. But this I mean that clicking on some part of the nav bar will reposition the selection rectangle there. (think time navigation in videos like youtube)

**Comment by marionleborgne** [comment]
@brev nice job with making the loading icon of the left menu consistent with the rest. The app really looks like the mockups now :smile:

**Comment by brev** [comment]
@marionleborgne thanks! Looking into the new click handler to see if easy or not, now.

**Comment by brev** [comment]
Still WIP. @marionleborgne: Clicking on range selector now re-positions it. But, this broke a few smaller edge cases I need to clean up still. Won't be long.

**Comment by brev** [comment]
final testing...

**Comment by brev** [comment]
ok @marionleborgne could you test again? Edge cases are fixed, and range selector mouse cursor is always `pointer` like on YouTube.

**Comment by marionleborgne** [comment]
@brev thanks! testing just now :+1: will let you know

**Comment by marionleborgne** [comment]
:+1: Very cool!

**Pull request merged**
