### PR TITLE
Specify unicorn_backend location via PYTHONPATH env var and launch python modules via -m option from javascript

### PR DESCRIPTION
**Pull request by vitaly-krugl**
@marionleborgne, would this work? Please try it out.

CC @oxtopus @brev

### CODE REVIEW

**Comment by vitaly-krugl** [comment]
@oxtopus, this change in the environment variables with which the backend apps are launched appears to make absolute imports succeed in those python backend apps. However, the fact that this was necessary to get it to work might expose a flaw in the Unicorn build process: isn't the build supposed to get the unicorn_backend  in the same place as the other 3rd-party packages, such that its imports would work correctly without any additional magic???

**Comment by oxtopus** [comment]
I believe this new change is the right approach and not indicative of a flaw in the build process, but specific to the way that the unicorn app will be deployed in practice.

**Comment by vitaly-krugl** [comment]
I prototyped this solution, using duplicate code for setting up PYTHONPATH in each of the js modules. I would prefer to have this logic in a shared function or perhaps in another obvious place where it would only run once. Ideally, instead of modifying `process.env`, we would instead make a copy of `process.env` and make our PYTHONPATH changes in the copy that is used for spawining the python apps. If someone can give me some pointers about how and where to do this, I would be glad to give it a try.

**Comment by lscheinkman** [comment]
Replaced by #667

**Pull request closed without merging**
