### PR TITLE
UNI-321: Update database schema

### PR DESCRIPTION
**Pull request by lscheinkman**
@marionleborgne @brev 
Please review

### CODE REVIEW

**Comment by brev** [comment]
@lscheinkman I'm getting an error on File Upload:
```
Unknown Error: Uncaught instance.rowOffset is required
  (anonymous function) @ FluxibleContext.js:241
  processImmediate @ timers.js:383
```
trying to find out more...

**Comment by lscheinkman** [comment]
@brev I fixed the schema issue but the `FileUpload` is not fully functional with this PR.
 It depends on **UNI-320** and **UNI-338**

**Comment by brev** [comment]
LGTM :+1: thanks

**Comment by lscheinkman** [comment]
@brev This should fix the `FileUpload` issue. Let me know if it works for you

**Comment by brev** [comment]
:+1: LGTM

**Pull request merged**
