### PR TITLE
Migrate GrokSolutions/grok-cli to numenta/numenta-apps/grok-cli

### PR DESCRIPTION
**Pull request by oxtopus**
cc @rhyolight @jcasner

### CODE REVIEW

**Comment by jcasner** [comment]
Why move this into the numenta-apps repo instead of moving to https://github.com/numenta/grok-cli?

**Comment by oxtopus** [comment]
@jcasner it's a grok client, just like `grok-mobile`.  It's explicitly tied to `grok`.

**Comment by jcasner** [comment]
Ok, that makes sense.

@rhyolight I'm OK with this change, and, while I suspect that it's OK, just want to confirm with you that having a totally different license for this package is OK within the numenta-apps repo...

**Comment by oxtopus** [comment]
@jcasner it's GPLv3, just like rest of grok.

**Comment by oxtopus** [comment]
Actually, now that I look at it, it's all sorts of screwed up license-wise.  There's https://github.com/oxtopus/numenta-apps/commit/7608f627b2b36aea502238cda33f0930a6e66f1f which switched it to GPLv3, but left the original Apache `LICENSE` file.  So now there's `LICENSE.txt` and `LICENSE`, which conflict with each-other.  The copyright headers were also never updated to reflect GPL.

Regardless, I think that's an issue to address separately.

**Comment by rhyolight** [comment]
Yes, as long as it is separated by directory and treated as a separate app,
each app can have a different license.

---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by rhyolight** [comment]
Ok to merge it and clean up the license stuff immediately after.

---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by jcasner** [comment]
:+1:

**Pull request merged**
