### PR TITLE
Make anomalyScore type check more general and add type of the offending object to the assertion message when typecheck of anomaly score fails

### LINKED ISSUE #891: Add type of the offending object to the assertion message when typecheck of anomaly score fails
model_swapper_interface.py asserts:

```
      assert isinstance(anomalyScore, (int, long, float)), (
        "Expected numeric anomaly score with status=0, but got: " +
        repr(anomalyScore))
```

A user reported an unexpected assertion failure: `AssertionError: Expected numeric anomaly score with status=0, but got: 1.0)` in an HTM Forum post https://discourse.numenta.org/t/my-installation-suddenly-failed-with-asertionerror-message/1389.

It would have been helpful for root-causing if the assertion message included the type of the offending object.

### PR DESCRIPTION
**Pull request by vitaly-krugl**
Fixes #891 

The goal of this PR is narrowly focused on improving the existing argument check and providing slightly more diagnostic info when the check fails, such as the initial failure described in https://discourse.numenta.org/t/my-installation-suddenly-failed-with-asertionerror-message/1389.

### CODE REVIEW

**Comment by vitaly-krugl** [comment]
Please review this tiny PR

**Comment by vitaly-krugl** [comment]
Please review this tiny PR

cc @oxtopus

**Comment by oxtopus** [comment]
`repr()` is the right thing to do, here, so I'm inclined to say no.

**Comment by vitaly-krugl** [comment]
Thanks @oxtopus, I addressed the feedback

**Comment by vitaly-krugl** [comment]
@oxtopus, after reflecting on our offline discussion, I came back to the goal of the checks in the constructor in the first place, which is to validate its input args on entry.

This more generic check will work:
```
In [17]: import numbers

In [18]: all(isinstance(num, numbers.Number) for num in [numpy.float(1.0), numpy.float32(1.0), 1.0, 1, int(1), long(1), float(9)])
Out[18]: True
```

**Comment by vitaly-krugl** [comment]
Merge approved by @scottpurdy in offline discussion.

**Pull request merged**
