### PR TITLE
testing. do not merge. explore model runner code

### PR DESCRIPTION
**Pull request by brev**
TEST - DO NOT MERGE

### CODE REVIEW

**Comment by brev** [comment]
hi @marionleborgne, you asked for some help on Fri. afternoon just as my brain was melting from a long week - I don't think I was very helpful, sorry.  Over the weekend I mocked out what we discussed a bit, but wasn't able to finish in a timely manner. This might be helpful, or too late :)  Just in case.

@lscheinkman @jcasner I wasn't able to keep up over the weekend as planned, so I'll see you in a few minutes, and will try catching up later tonight. thanks.

Also, you all might want to check this out:
https://github.com/kriskowal/gtor
Great for explaining what Streams, Promises, etc, are.

**Comment by brev** [comment]
anyone can close this at any time. I will clean up later if nobody beats me to it.

**Comment by lscheinkman** [comment]
@brev  
Thanks for the link explaining Streams, Promises, etc.
However this PR is implementing the same as @marionleborgne 's PR #318 . 
Please coordinate with @marionleborgne before merging

**Comment by marionleborgne** [comment]
@brev thanks for the link. #318 is implemented and merged. we can probably close this PR now, right?

**Comment by brev** [comment]
@lscheinkman @marionleborgne yes, this was just for educational purposes. closing.

**Pull request closed without merging**
