### PR TITLE
UNI-319: Add application packager and installers

### PR DESCRIPTION
**Pull request by lscheinkman**
Use [electron-builder](https://www.npmjs.com/package/electron-builder) to package the app.

>**NOTE**: These scripts will also create artifacts for the **auto-updater**. We would still need to add code supporting **auto-updater** in the app

Sorry for the large PR, I had to rename the `js` folder to `app` (242966b) so it would be compatible with `electron` directory structure. Most of the relevant changes were made in the other 2 commits (eecc44e, 1531fb6)

@marionleborgne Please try it out and let me know if it works for you.

Here are the commands to build the application and installers:
### Package OSX Application (.app)
```
npm run clean && npm install && npm run prepare && npm run pack:osx
```
### Create OSX Installation image (.dmg)
```
npm run clean && npm install && npm run prepare && npm run dist:osx
```
### Package Windows Application (.exe)
```
npm run clean && npm install && npm run prepare && npm run pack:win
```
### Create Windows Installer (setup.exe)
```
npm run clean && npm install && npm run prepare && npm run dist:win
```

Check `/dist` folder for results.

### CODE REVIEW

**Comment by brev** [comment]
Starting to explore on my side

**Comment by brev** [comment]
Hi @lscheinkman. App works great for me, but a few tooling issues:

`npm run test` ➜ `Error: Cannot find module 'csv-streamify'` - Tests see to be missing the new split `app/package.json` dependencies?

`npm run docs` ➜ Five warnings, and then 1 fatal failure, on ES7 `/node_modules/` directory (even though plugin seems correctly installed to me).

**Comment by brev** [comment]
@lscheinkman does this help?

background

**Comment by brev** [comment]
Mac `pack` and `dist` work great for me!  Trying Windows next.

**Comment by lscheinkman** [comment]
@brev Thank you for the feedback!
Don't worry about the windows yet, I found a problem and will try to fix it tomorrow, will let you know when i get the windows working.

**Comment by lscheinkman** [comment]
@brev I've addressed your feedback but was not able to get windows to work, some problem with `leveldown` bindings. I will merge this PR to cover the `OSX` build and create a separate PR for windows.
CC: @marionleborgne

**Pull request merged**
